name: Build Debian Package

on:
  push:
    branches: [master, main]
    tags:
      - "v*"
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    # No container needed, use native Ubuntu runner

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libgl1-mesa-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.0"
          host: "linux"
          target: "desktop"
          arch: "linux_gcc_64"
          modules: "qtwebchannel qthttpserver qtwebengine qtpositioning qtwebsockets"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Backend
        run: |
          mkdir -p backend/build
          cd backend/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Bundle Frontend with Backend
        run: |
          mkdir -p backend/build/bin/frontend
          cp -r frontend/out/* backend/build/bin/frontend/

      - name: Create Debian Package
        run: |
          # Create package structure
          PKG_DIR="daily-reminder_1.0.0_amd64"
          mkdir -p "$PKG_DIR/DEBIAN"
          mkdir -p "$PKG_DIR/usr/bin"
          mkdir -p "$PKG_DIR/usr/share/daily-reminder"
          mkdir -p "$PKG_DIR/usr/share/applications"

          # Copy files
          cp backend/build/backend "$PKG_DIR/usr/bin/daily-reminder"
          cp -r frontend/out/* "$PKG_DIR/usr/share/daily-reminder/"

          # Create desktop entry
          cat > "$PKG_DIR/usr/share/applications/daily-reminder.desktop" <<'EOF'
          [Desktop Entry]
          Name=Daily Reminder
          Comment=Calendar application with reminders
          Exec=/usr/bin/daily-reminder
          Icon=appointment-soon
          Terminal=false
          Type=Application
          Categories=Office;Calendar;
          EOF

          # Create control file
          cat > "$PKG_DIR/DEBIAN/control" <<'EOF'
          Package: daily-reminder
          Version: 1.0.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libqt6core6, libqt6gui6, libqt6widgets6, libqt6webenginecore6, libqt6webenginewidgets6, libqt6webchannel6, libqt6network6, libqt6sql6, libqt6httpserver6, libnotify-bin
          Maintainer: illufoxKusanagi
          Description: Desktop calendar application with reminders
           A desktop calendar application for managing daily activities with reminders,
           built with Qt 6 (backend REST API) and Next.js (frontend UI).
          EOF

          # Build the package
          dpkg-deb --build "$PKG_DIR"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DailyReminder-Debian-amd64
          path: "*.deb"
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.deb"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
